---
users: ${userlist}

easyrsa_reinit_existent: False

vpn_network: 10.19.48.0/24
vpn_network_ipv6: 'fd9d:bc11:4020::/48'

wireguard_enabled: false

server_name: "{{ ansible_ssh_host }}"
IP_subject_alt_name: "{{ ansible_ssh_host }}"

strongswan_log_level: 2

dns_encryption: true
dns_encryption_provider: google
local_service_ip: 172.16.0.1

pkcs12_PayloadCertificateUUID: "{{ 900000 | random | to_uuid | upper }}"
VPN_PayloadIdentifier: "{{ 800000 | random | to_uuid | upper }}"
CA_PayloadIdentifier: "{{ 700000 | random | to_uuid | upper }}"

BetweenClients_DROP: Y

cloud_providers:
  local:

SSH_keys:
  comment: algo@ssh
  private: configs/algo.pem
  public: configs/algo.pem.pub

congrats:
  common: "# Algo setup complete at {{ ansible_ssh_host }}"
  p12_pass: "# User cert passphrase: {{ easyrsa_p12_export_password }}"

fail_hint:
  - Sorry, but something went wrong!
